### ISSUE TITLE
Results are stored in json format

### ISSUE THREAD

**Issue by mo-tech55** [gosom/google-maps-scraper#17] opened 2023-09-25 14:21 UTC
I followed the steps mentioned in [this section](https://github.com/gosom/google-maps-scraper#using-database-provider-postgresql) but the results are stored in json format in one column which makes it hard to work with.
![image](https://github.com/gosom/google-maps-scraper/assets/55327453/ea7d735c-3c9e-4083-9700-c34995c53cb8)

I saw in your blog in [this section](https://blog.gkomninos.com/distributed-google-maps-scraping#heading-google-maps-scraper-deployment) that you created a table with the columns you want. I tried that but when I do that the scraper stops after about three listings. No results are inserted in the database. I guess the code breaks here because the table has an unexpected format.

**Comment by gosom** [comment] 2023-09-25 17:07
hi @mo-tech55 ,

the first version was with a table with a column per attribute extracted. 
However, with the addition of may additional attributes it was not easy to maintain. 

Thus, I decided to store the results in a JSOB column .

The blog post is now outdated, judging from the screenshot it seems like you managed to run the code with success.

You have two options:
- create your own exported
- create a postgreSQL to simplfy the query of the data you are interested in
- post process the data with a programming language and re-insert to a table structure of your choice if you are not very familiar with JSOB operations.

This is not a bug and it's a deliberate decision. 

I am closing this ticket. 

if you need something else feel free to re-open

**Closed by gosom** 2023-09-25 17:07 UTC
