### ISSUE TITLE
Hi i got some issue in here

### ISSUE THREAD

**Issue by galileor97** [gosom/google-maps-scraper#1] opened 2023-04-30 18:15 UTC
=========================================","status":"failed","duration":150831.139,"time":"2023-04-30T18:14:18.227687Z","message":"job finished"}
{"level":"error","component":"scrapemate","error":"could not send message to server: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for selector \"button[aria-label='Reject all']\"\n============================================================","time":"2023-04-30T18:14:18.228161Z","message":"error while processing job"}

**Comment by gosom** [comment] 2023-05-01 09:11
Can you please provide more information? 

Do you experience this while trying the example:

```
touch results.csv && docker run -v $PWD/example-queries.txt:/example-queries -v $PWD/results.csv:/results.csv gosom/google-maps-scraper -depth 1 -input /example-queries -results /results.csv
```

Or you modified the code, like for example trying using a different country/language?

**Comment by galileor97** [comment] 2023-05-01 20:47
I'm trying to run on my host.

./google-maps-scraper -input example-queries.txt -results restaurants-in-cyprus.csv
I just edited the example-queries to my keyword and country target.

My Machine is M1 Macbook

**Comment by gosom** [comment] 2023-05-07 06:56
I added support to pass the language parameter. 

Please try again by specifying you language code:

Example:

```
./google-maps-scraper -input example-queries.txt -results restaurants-in-cyprus.csv -lang el
```

you can find a list of the supported language codes here:

https://serpapi.com/google-languages


please let me know if that works if possible.

best

**Comment by gosom** [comment] 2023-05-13 14:30
The issue is resolved and I am closing it.

**Closed by gosom** 2023-05-13 14:30 UTC
